import { getDB } from "../../../lib/mongodb.js";
import { requireAuth } from "../../../lib/auth.js";

export default async (request) => {
  if (request.method !== "POST") {
      return Response.json(
            { success: false, message: "Method not allowed" },
                  { status: 405 }
                      );
                        }

                          try {
                              const user = requireAuth(request.headers);

                                  if (
                                        user.role !== "admin" &&
                                              user.role !== "librarian"
                                                  ) {
                                                        return Response.json(
                                                                {
                                                                          success: false,
                                                                                    message: "Only admin or librarian can add books"
                                                                                            },
                                                                                                    { status: 403 }
                                                                                                          );
                                                                                                              }

                                                                                                                  const data = await request.json();

                                                                                                                      const {
                                                                                                                            title,
                                                                                                                                  author,
                                                                                                                                        isbn,
                                                                                                                                              department,
                                                                                                                                                    genre,
                                                                                                                                                          description,
                                                                                                                                                                coverImage,
                                                                                                                                                                      totalCopies,
                                                                                                                                                                            location
                                                                                                                                                                                } = data;

                                                                                                                                                                                    if (
                                                                                                                                                                                          !title ||
                                                                                                                                                                                                !author ||
                                                                                                                                                                                                      !department
                                                                                                                                                                                                          ) {
                                                                                                                                                                                                                return Response.json(
                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                  success: false,
                                                                                                                                                                                                                                            message:
                                                                                                                                                                                                                                                        "Title, author and department are required"
                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                        { status: 400 }
                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                      const copies = Number(totalCopies) || 1;

                                                                                                                                                                                                                                                                                          const book = {
                                                                                                                                                                                                                                                                                                title,
                                                                                                                                                                                                                                                                                                      author,
                                                                                                                                                                                                                                                                                                            isbn: isbn || "",
                                                                                                                                                                                                                                                                                                                  department,
                                                                                                                                                                                                                                                                                                                        genre: genre || "Academic",
                                                                                                                                                                                                                                                                                                                              description: description || "",
                                                                                                                                                                                                                                                                                                                                    coverImage: coverImage || "",
                                                                                                                                                                                                                                                                                                                                          totalCopies: copies,
                                                                                                                                                                                                                                                                                                                                                availableCopies: copies,
                                                                                                                                                                                                                                                                                                                                                      location: location || "",
                                                                                                                                                                                                                                                                                                                                                            createdAt: new Date(),
                                                                                                                                                                                                                                                                                                                                                                  updatedAt: new Date()
                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                          const db = await getDB();

                                                                                                                                                                                                                                                                                                                                                                              const result = await db
                                                                                                                                                                                                                                                                                                                                                                                    .collection("books")
                                                                                                                                                                                                                                                                                                                                                                                          .insertOne(book);

                                                                                                                                                                                                                                                                                                                                                                                              return Response.json({
                                                                                                                                                                                                                                                                                                                                                                                                    success: true,
                                                                                                                                                                                                                                                                                                                                                                                                          message: "Book added successfully",
                                                                                                                                                                                                                                                                                                                                                                                                                bookId: result.insertedId.toString()
                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                          console.error(error);

                                                                                                                                                                                                                                                                                                                                                                                                                              return Response.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                            success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    message: error.message || "Unable to add book"
                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                { status: 500 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };