import { ObjectId } from "mongodb";
import { getDB } from "../../../lib/mongodb.js";
import { requireAuth } from "../../../lib/auth.js";

export default async (request) => {
  if (request.method !== "POST") {
      return Response.json(
            { success: false, message: "Method not allowed" },
                  { status: 405 }
                      );
                        }

                          try {
                              const admin = requireAuth(request.headers);

                                  if (
                                        admin.role !== "admin" &&
                                              admin.role !== "librarian"
                                                  ) {
                                                        return Response.json(
                                                                {
                                                                          success: false,
                                                                                    message: "Only admin or librarian can process returns"
                                                                                            },
                                                                                                    { status: 403 }
                                                                                                          );
                                                                                                              }

                                                                                                                  const { borrowId } = await request.json();

                                                                                                                      if (!borrowId) {
                                                                                                                            return Response.json(
                                                                                                                                    {
                                                                                                                                              success: false,
                                                                                                                                                        message: "Borrow ID is required"
                                                                                                                                                                },
                                                                                                                                                                        { status: 400 }
                                                                                                                                                                              );
                                                                                                                                                                                  }

                                                                                                                                                                                      const db = await getDB();

                                                                                                                                                                                          const borrowResult = await db
                                                                                                                                                                                                .collection("borrowings")
                                                                                                                                                                                                      .findOneAndUpdate(
                                                                                                                                                                                                              {
                                                                                                                                                                                                                        _id: new ObjectId(borrowId),
                                                                                                                                                                                                                                  status: { $in: ["borrowed", "overdue"] }
                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                            $set: {
                                                                                                                                                                                                                                                                        status: "returned",
                                                                                                                                                                                                                                                                                    returnDate: new Date(),
                                                                                                                                                                                                                                                                                                updatedAt: new Date()
                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                    returnDocument: "before"
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                      const borrow = borrowResult;

                                                                                                                                                                                                                                                                                                                                                          if (!borrow) {
                                                                                                                                                                                                                                                                                                                                                                return Response.json(
                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                  success: false,
                                                                                                                                                                                                                                                                                                                                                                                            message:
                                                                                                                                                                                                                                                                                                                                                                                                        "Borrowing record not found or already returned"
                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                        { status: 404 }
                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                      await db.collection("books").updateOne(
                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    _id: new ObjectId(borrow.bookId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $inc: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  availableCopies: 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  $set: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            updatedAt: new Date()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return Response.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              message: "Book returned successfully",

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    book: borrow.bookTitle,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          returnDate: new Date()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error(error);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return Response.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              message:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        error.message || "Unable to return book"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { status: 500 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };