import { useEffect, useState } from "react";
import api from "../services/api";

const departments = [
  "",
    "MBA",
      "Civil",
        "ECE",
          "Mechanical",
            "Diploma",
              "AI",
                "EEE",
                  "MCA"
                  ];

                  const genres = [
                    "",
                      "Novel",
                        "Academic",
                          "Technical",
                            "Reference",
                              "Science",
                                "Fiction",
                                  "Biography"
                                  ];

                                  export default function Books() {
                                    const [books, setBooks] = useState([]);

                                      const [search, setSearch] =
                                          useState("");

                                            const [department, setDepartment] =
                                                useState("");

                                                  const [genre, setGenre] =
                                                      useState("");

                                                        const [loading, setLoading] =
                                                            useState(true);

                                                              const fetchBooks = async () => {
                                                                  setLoading(true);

                                                                      try {
                                                                            const response =
                                                                                    await api.get("/books/get-books", {
                                                                                              params: {
                                                                                                          search,
                                                                                                                      department,
                                                                                                                                  genre
                                                                                                                                            }
                                                                                                                                                    });

                                                                                                                                                          setBooks(response.data.books);

                                                                                                                                                              } catch (error) {
                                                                                                                                                                    console.error(error);
                                                                                                                                                                        } finally {
                                                                                                                                                                              setLoading(false);
                                                                                                                                                                                  }
                                                                                                                                                                                    };

                                                                                                                                                                                      useEffect(() => {
                                                                                                                                                                                          const timer =
                                                                                                                                                                                                setTimeout(fetchBooks, 300);

                                                                                                                                                                                                    return () => clearTimeout(timer);

                                                                                                                                                                                                      }, [search, department, genre]);

                                                                                                                                                                                                        return (
                                                                                                                                                                                                            <div className="page-container">

                                                                                                                                                                                                                  <h1 className="page-title">
                                                                                                                                                                                                                          Library Books
                                                                                                                                                                                                                                </h1>

                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                              className="search-bar"
                                                                                                                                                                                                                                                      placeholder="Search books, authors or ISBN..."

                                                                                                                                                                                                                                                              value={search}

                                                                                                                                                                                                                                                                      onChange={(e) =>
                                                                                                                                                                                                                                                                                setSearch(e.target.value)
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                    <div className="filters">

                                                                                                                                                                                                                                                                                                            <select
                                                                                                                                                                                                                                                                                                                      value={department}

                                                                                                                                                                                                                                                                                                                                onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                            setDepartment(e.target.value)
                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                        <option value="">
                                                                                                                                                                                                                                                                                                                                                                                    All Departments
                                                                                                                                                                                                                                                                                                                                                                                              </option>

                                                                                                                                                                                                                                                                                                                                                                                                        {departments.slice(1).map(
                                                                                                                                                                                                                                                                                                                                                                                                                    (item) => (

                                                                                                                                                                                                                                                                                                                                                                                                                                  <option
                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={item}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={item}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {item}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </option>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={genre}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setGenre(e.target.value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            All Genres
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </option>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {genres.slice(1).map(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            (item) => (

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          key={item}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={item}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {item}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </option>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {loading ? (

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Loading books...</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : books.length === 0 ? (

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>No books found.</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="books-grid">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {books.map((book) => (

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="book-card"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={book._id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {book.coverImage && (

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  src={book.coverImage}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alt={book.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>{book.title}</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="book-meta">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Author: {book.author}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="book-meta">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Department: {book.department}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="book-meta">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Genre: {book.genre}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Available:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {book.availableCopies}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }