import { useAuth } from "../context/AuthContext";
import { Link } from "react-router-dom";

export default function Dashboard() {
  const { user } = useAuth();

    return (
        <div className="dashboard">

              <section className="welcome-card">
                      <div>
                                <p>WELCOME BACK</p>

                                          <h1>
                                                      Hello, {user?.name} 👋
                                                                </h1>

                                                                          <span>
                                                                                      {user?.department} Department
                                                                                                </span>
                                                                                                        </div>

                                                                                                                {user?.photoUrl && (
                                                                                                                          <img
                                                                                                                                      src={user.photoUrl}
                                                                                                                                                  alt="Profile"
                                                                                                                                                              className="profile-photo"
                                                                                                                                                                        />
                                                                                                                                                                                )}
                                                                                                                                                                                      </section>

                                                                                                                                                                                            <div className="dashboard-grid">

                                                                                                                                                                                                    <Link
                                                                                                                                                                                                              to="/departments"
                                                                                                                                                                                                                        className="dashboard-card"
                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                          📚
                                                                                                                                                                                                                                                    <h3>Departments</h3>
                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                          Browse academic resources
                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                            </Link>

                                                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                                              to="/books"
                                                                                                                                                                                                                                                                                                                        className="dashboard-card"
                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                          📖
                                                                                                                                                                                                                                                                                                                                                    <h3>Books</h3>
                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                          Search the library collection
                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                            </Link>

                                                                                                                                                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                                                                                                                                              to="/my-books"
                                                                                                                                                                                                                                                                                                                                                                                                                        className="dashboard-card"
                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                          📅
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3>My Books</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Track due dates
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              to="/request-book"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="dashboard-card"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          🙋
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3>Request Book</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Request a new book
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              to="/library-visit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="dashboard-card"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ✍️
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3>Library Visit</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Check in or check out
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }