import { Link } from "react-router-dom";
import {
  BookOpen,
    Building2,
      Bell,
        Clock
        } from "lucide-react";

        export default function Home() {
          return (
              <div className="home-page">

                    <section className="hero">
                            <div>
                                      <p className="hero-tag">
                                                  DIGITAL COLLEGE LIBRARY
                                                            </p>

                                                                      <h1>
                                                                                  Smart Library
                                                                                              <span> Management Portal</span>
                                                                                                        </h1>

                                                                                                                  <p className="hero-text">
                                                                                                                              Search books, access academic resources,
                                                                                                                                          manage borrowing, track due dates and
                                                                                                                                                      receive reminders.
                                                                                                                                                                </p>

                                                                                                                                                                          <div className="hero-buttons">
                                                                                                                                                                                      <Link to="/register" className="primary-btn">
                                                                                                                                                                                                    Get Started
                                                                                                                                                                                                                </Link>

                                                                                                                                                                                                                            <Link to="/login" className="secondary-btn">
                                                                                                                                                                                                                                          Login
                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                <div className="hero-icon">
                                                                                                                                                                                                                                                                                          <BookOpen size={150} />
                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                              <section className="features">

                                                                                                                                                                                                                                                                                                                      <div className="feature-card">
                                                                                                                                                                                                                                                                                                                                <BookOpen size={32} />
                                                                                                                                                                                                                                                                                                                                          <h3>Digital Resources</h3>
                                                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                                                Books, thesis, projects,
                                                                                                                                                                                                                                                                                                                                                                            records and journals.
                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                      <div className="feature-card">
                                                                                                                                                                                                                                                                                                                                                                                                                <Building2 size={32} />
                                                                                                                                                                                                                                                                                                                                                                                                                          <h3>Departments</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                Resources organized department-wise.
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="feature-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Clock size={32} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>Borrow Tracking</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Track borrowed books and due dates.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="feature-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Bell size={32} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3>SMS Reminder</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Get notified before your due date.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }