import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import api from "../services/api";
import { useAuth } from "../context/AuthContext";

export default function Login() {
  const navigate = useNavigate();
    const { login } = useAuth();

      const [loginId, setLoginId] = useState("");
        const [password, setPassword] = useState("");

          const [loading, setLoading] = useState(false);
            const [message, setMessage] = useState("");

              const handleLogin = async (e) => {
                  e.preventDefault();

                      setLoading(true);
                          setMessage("");

                              try {
                                    const response = await api.post(
                                            "/auth/login",
                                                    {
                                                              loginId,
                                                                        password
                                                                                }
                                                                                      );

                                                                                            const data = response.data;

                                                                                                  login(data.token, data.user);

                                                                                                        navigate("/dashboard");

                                                                                                            } catch (error) {
                                                                                                                  setMessage(
                                                                                                                          error.response?.data?.message ||
                                                                                                                                  "Login failed"
                                                                                                                                        );
                                                                                                                                            } finally {
                                                                                                                                                  setLoading(false);
                                                                                                                                                      }
                                                                                                                                                        };

                                                                                                                                                          return (
                                                                                                                                                              <div className="auth-page">

                                                                                                                                                                    <form
                                                                                                                                                                            className="auth-card"
                                                                                                                                                                                    onSubmit={handleLogin}
                                                                                                                                                                                          >

                                                                                                                                                                                                  <h2>Welcome Back</h2>

                                                                                                                                                                                                          <p>
                                                                                                                                                                                                                    Login to your Smart Library account
                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                    {message && (
                                                                                                                                                                                                                                              <div className="error-message">
                                                                                                                                                                                                                                                          {message}
                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                    <label>
                                                                                                                                                                                                                                                                                              Register Number / ID / Phone
                                                                                                                                                                                                                                                                                                      </label>

                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                        type="text"
                                                                                                                                                                                                                                                                                                                                  value={loginId}
                                                                                                                                                                                                                                                                                                                                            onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                        setLoginId(e.target.value)
                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                            <label>Password</label>

                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                              type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                        value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                              setPassword(e.target.value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="primary-btn full-btn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? "Logging in..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          : "Login"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="auth-footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Don't have an account?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link to="/register">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Register here
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }