import { useState } from "react";
import api from "../services/api";
import { useAuth } from "../context/AuthContext";

export default function RequestBook() {
  const { user } = useAuth();

    const [form, setForm] = useState({
        bookName: "",
            author: "",
                department: user?.department || "",
                    reason: "",
                        priority: "normal"
                          });

                            const [message, setMessage] = useState("");
                              const [loading, setLoading] = useState(false);

                                function updateField(field, value) {
                                    setForm((previous) => ({
                                          ...previous,
                                                [field]: value
                                                    }));
                                                      }

                                                        async function handleSubmit(event) {
                                                            event.preventDefault();

                                                                setLoading(true);
                                                                    setMessage("");

                                                                        try {
                                                                              const response = await api.post(
                                                                                      "/requests/create-request",
                                                                                              form
                                                                                                    );

                                                                                                          setMessage(response.data.message);

                                                                                                                setForm({
                                                                                                                        bookName: "",
                                                                                                                                author: "",
                                                                                                                                        department: user?.department || "",
                                                                                                                                                reason: "",
                                                                                                                                                        priority: "normal"
                                                                                                                                                              });
                                                                                                                                                                  } catch (error) {
                                                                                                                                                                        setMessage(
                                                                                                                                                                                error.response?.data?.message ||
                                                                                                                                                                                          "Unable to submit request"
                                                                                                                                                                                                );
                                                                                                                                                                                                    } finally {
                                                                                                                                                                                                          setLoading(false);
                                                                                                                                                                                                              }
                                                                                                                                                                                                                }

                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                      <div className="page-container">
                                                                                                                                                                                                                            <h1 className="page-title">Request a Book</h1>

                                                                                                                                                                                                                                  <form className="form-card" onSubmit={handleSubmit}>
                                                                                                                                                                                                                                          {message && (
                                                                                                                                                                                                                                                    <div className="info-message">
                                                                                                                                                                                                                                                                {message}
                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                          <label>Book Name</label>
                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                            className="form-input"
                                                                                                                                                                                                                                                                                                                      value={form.bookName}
                                                                                                                                                                                                                                                                                                                                onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                            updateField("bookName", e.target.value)
                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                <label>Author</label>
                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                  className="form-input"
                                                                                                                                                                                                                                                                                                                                                                                                            value={form.author}
                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                  updateField("author", e.target.value)
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label>Department</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="form-input"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={form.department}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              updateField("department", e.target.value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label>Reason for Request</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="form-input"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rows="4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={form.reason}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              updateField("reason", e.target.value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label>Priority</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="form-input"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={form.priority}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          updateField("priority", e.target.value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="normal">Normal</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="high">High</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="primary-btn full-btn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {loading
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ? "Submitting..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : "Submit Request"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }