import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import api from "../services/api";

const resourceTypes = [
  "books",
    "thesis",
      "mini-project",
        "major-project",
          "record",
            "journal"
            ];

            export default function Resources() {
              const [searchParams] = useSearchParams();

                const department = searchParams.get("department") || "";

                  const [resources, setResources] = useState([]);
                    const [type, setType] = useState("");
                      const [loading, setLoading] = useState(true);

                        useEffect(() => {
                            async function fetchResources() {
                                  setLoading(true);

                                        try {
                                                const response = await api.get(
                                                          "/resources/get-resources",
                                                                    {
                                                                                params: {
                                                                                              department: department,
                                                                                                            type: type
                                                                                                                        }
                                                                                                                                  }
                                                                                                                                          );

                                                                                                                                                  setResources(response.data.resources || []);
                                                                                                                                                        } catch (error) {
                                                                                                                                                                console.error("Error loading resources:", error);
                                                                                                                                                                        setResources([]);
                                                                                                                                                                              } finally {
                                                                                                                                                                                      setLoading(false);
                                                                                                                                                                                            }
                                                                                                                                                                                                }

                                                                                                                                                                                                    fetchResources();
                                                                                                                                                                                                      }, [department, type]);

                                                                                                                                                                                                        return (
                                                                                                                                                                                                            <div className="page-container">

                                                                                                                                                                                                                  <h1 className="page-title">
                                                                                                                                                                                                                          {department
                                                                                                                                                                                                                                    ? `${department} Resources`
                                                                                                                                                                                                                                              : "Academic Resources"}
                                                                                                                                                                                                                                                    </h1>

                                                                                                                                                                                                                                                          <div className="filters">
                                                                                                                                                                                                                                                                  <select
                                                                                                                                                                                                                                                                            value={type}
                                                                                                                                                                                                                                                                                      onChange={(e) => setType(e.target.value)}
                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                        <option value="">All Resources</option>

                                                                                                                                                                                                                                                                                                                  {resourceTypes.map((item) => (
                                                                                                                                                                                                                                                                                                                              <option key={item} value={item}>
                                                                                                                                                                                                                                                                                                                                            {item}
                                                                                                                                                                                                                                                                                                                                                        </option>
                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                          </select>
                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                      {loading && <p>Loading resources...</p>}

                                                                                                                                                                                                                                                                                                                                                                                            {!loading && resources.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                    <p>No resources available.</p>
                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                {!loading && resources.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="resources-grid">

                                                                                                                                                                                                                                                                                                                                                                                                                                  {resources.map((resource) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="resource-card"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          key={resource._id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3>{resource.title}</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <strong>Type:</strong>{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {resource.type}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <strong>Department:</strong>{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {resource.department}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {resource.author && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <strong>Author:</strong>{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {resource.author}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {resource.description && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>{resource.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {resource.fileUrl && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        href={resource.fileUrl}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            rel="noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="primary-btn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Open Resource
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }